import { ROAST } from "@prisma/client";

export const coffee = [
  {
  name: "Black Apple Espresso",
  brand: "Airship",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcwxu7wf7AdcEiIdH6eswxTy8_mKMkeiMrnrqjWv46u2izKiomYqfzB0UdwegNQTh8t1TB3bzXy9J9aZspdOPWs0NO3AfNLF4koWoCIDjTEfz4pycU=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHc4OwbTDac5V4cxCYbgqf1UNMwajlBjZnTXMxqwV9MleMCa31lOcUnd7D9SNq2Kq72T6Vqd6FgdesIZga9ok-uZ4ArSxwnL0MrrpcmA9eFqq6QqBak=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "23.50",
  webAddress: "black-apple-espresso",
  description: "With its syrupy body, tons of chocolaty sweetness, and splash of juicy cherry acidity, this one's ready to become your new favorite espresso."
},
  {
  name: "Black Bear Blend",
  brand: "Airship",
  country: "El Salvador",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHc4DcJhE3md-w4zfuMVhQWgoQgyzwQaNbX49SZH-oSM5Ds2fFebulbEUKtDWWt7_s8UdfNkGM9Uf_OEbgLpJPW6YqanlpNsIZM4KuZSEUPDE0TUZvk=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdIdpKm0dzbxUm7OykPTaCsxTn4uQ0DTA2btw-_k0j1GgUTpjZoRSwbj_QE7Sh4xkvBxcLfGULUeGqo5xaA8ZjsTevoiqVNV9fpKeqnI8H3DCSV0Pg=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "18.50",
  webAddress: "black-bear-blend",
  description: "Deeply sweet and chocolaty, with a kiss of roastiness pairing beautifully with notes of toasted walnut."
},
  {
  name: "Colombia Sugar Cane Decaf",
  brand: "Airship",
  country: "Colombia",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdhzycNiRWHffgtGPQWfuu_3wcZYiUaJELoSD5C92aI0o6JP_UaAq2UPj8ayVomGIPcRkJBIJC6qYFvuyR7GRw9UHoE-wc6l4zuDqkBy8pAf10d8vs=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcKb4seRH3_sR83RDZ9RqhbNf4U6ozd8LVGiVTQQ7G5CRDGeIGncH4ftfgfkb6EaG-naq-rq8VbZDR6MbSUyl-KYx3-oK9_Hj80OZ1axh-ftU0RdB8=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$18.50",
  webAddress: "colombia-sugar-cane-decaf",
  description: "Like its name suggests, a sugar cane-based process removes the caffeine here—but leaves this coffee’s superior integrity, and drinkability, totally intact."
},
  {
  name: "Ethiopia Kochere",
  brand: "Airship",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdx69LdEYv94dGD8Wk0wCkBK-ARdIST36MvUowxUk-9z1IJOqLxmP6RYFFBxt5r5FP_VAjlRsqB4chK4HlFjEGAGnQbzRkPmudrA86ZGMAtg94vLB8=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfuvGvrZgGLasPpW9APUkXkPNQ8V5tMK2yMcGXRPNdohYe0JL99YKkOh0RtsALTmfFgPqhJ3MWs3gDhBkAF48FCteFqHHiURvGeeaQKIJtSLx5DS9o=w1920-h1080"],
  roast: ROAST.LIGHT,
  price: "$23.50",
  webAddress: "ethiopia-kochere-airship",
  description: "How about starting your day with sugared berries and sunshine? This Ethiopian summer stunner delivers lush berry sweetness in a rich, smooth body."
},
  {
  name: "Night Moves",
  brand: "Airship",
  country: "El Salvador",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcwA1FKoM7I9d-Z1v_NLHXaQkm1nPZ1GGdMBmAwUYGSUmM3hlHllbfwwLeT4flrvA3J_K39uUvOSaQdKDhxxtpn1oTlxKpo8LcVwiQv98QNIt1HoQ4=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHduPv88Ki-Cx-jQ6YOtJKt1Baqd0Qa9rAktPyiZ3K68l-RfSZpMiqn8oWB4T_K1aOMVLQiXnwWQNTFPC7gHW5k7SNof2ofO7dhcKHON7se7dhflhpc=w1920-h1080"],
  roast: ROAST.DARK,
  price: "$18.50",
  webAddress: "night-moves",
  description: "A rich body and dense, roasty sweetness are complimented by notes of cocoa and a hint of zesty orange aromatics."
},
{
  name: "Sumatra Kerinci",
  brand: "Airship",
  country: "Indonesia",
  region: "Asia",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHffb7TbWZSWKsZu-mjPR5Z5jFvYvn6wKvpKS40ybErnvfWtBLij0dyRqBaZMBvSLkvvNS1I6EjWov9IjqzTG9QgC8Q_i5U6NXWXsYx4RMSUlYonUGk=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeKPq2WrczSzKSq9quri7yR_8oSvhIvxHi9I-vOxvl2PFoJJmFQQ-yH3kc72hiL2psplJdFMPBpB_7_q7Apyy7YYF03QcFM6JdikybTb8xdBuimQ34=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$18.50",
  webAddress: "sumatra-kerinci",
  description: "Plenty of bright grapefruit acidity and deep plum sweetness rounds out a comforting earthiness in this satisfying cup."
},
{
  name: "Black Velvet",
  brand: "Atomic",
  country: "Honduras",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdMEJwctfm22DV6nFo1--Hcum8Lg6EvQ4fo08NVsrHeMce8kBbU_81WQJDGWtTfILZk_MFjoZQb-Pw_eQtaqZzigBgO0993xDu8mALtjq_qmZnpd6c=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHd2KJQQ8HWG4MRrCY4IzErksWY5gh--NcyLah0TXTgt0OHGQoTl_XIYjiMLq7mGkmk-Pc3CmlrJQMs2WyMzxl-tprgm4ikkAAeojbkUV-yCwHI8iQ4=w1920-h1080"],
  roast: ROAST.MEDIUM_DARK,
  price: "$18.50",
  webAddress: "black-velvet",
  description: "Silky smooth and dark as night, this blend features a hint of spice and a nutty sweetness that'll pair beautifully with a splash of your favorite milk, but is just as delicious on its own."
},
{
  name: "Cabot Street",
  brand: "Atomic",
  country: "Colombia",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHeO3EaItVD_oQVyJzwI8E3TNbaLQaVdqBrqK0g_q4OG8KVPnHnENbNKrORIPZgpszypW1U-YGwP4vdN8dT8qGf6e7v_ryqyRACl34jUa5BwjoWPE4U=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdRPg6mConmrXyRwxI6rIZY8RJZvuLmY3acwksQMNu8D6-THCuyHtJyVBieiGD4hwD-ZitsbeFbP9q7hKzsQyhbSAYI6Nid3MN2EfkhtYKkbslAi4c=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$18.50",
  webAddress: "cabot-street",
  description: "Sticky-bodied and jam-packed with fruity flavors, this coffee features a bright apple acidity that cools to reveal notes of fresh green grapes."
},
{
  name: "Diesel",
  brand: "Atomic",
  country: "Honduras",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHe98BmDuJyBWFlDtCvuLpHCaC9qrz7ABZ1CB39sqczPDyGZakKuU9h07C2XVax0faxVKgd7HaTOS4I1z3hOSttCiW_-DNDQxDffMpJU6DhXzRU4CPE=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdHa0b5_71zNU8xwpowBKuahuO0P_vWCr511wJjVv_98XDQtnShWNTmSHyWPn3mNj5wjGPiotl5Ns8HdNSJhfXt8NsE7GZN9i6z3ezJKtscQSUkfvc=w1920-h1080"],
  roast: ROAST.MEDIUM_DARK,
  price: "$18.50",
  webAddress: "diesel-coffee",
  description: "Dark, rich and energizing, here’s fuel for your morning (or afternoon, or evening). A bit of earthy smokiness gives it extra oomph."
},
{
  name: "Ethiopia Kochere",
  brand: "Atomic",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfj8JnEb79xP1hXwH3mRs1Tlp0HqczdVohUxcHbOQUDWUd-Rq1F-GH6abDI54ZzsT4Z9YOhrly5ItfS3Xvt3yRie3LDEOWPTjblYPp8wJRy9t3Uhgo=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHf1kx1cjaOKLw2BY4cWcdI2WL7XYu65WFx1sTors8Pt7mI-JP3NBy7wUFu6fSyUVquyDSc-wHgBDIBKvL5zn3TOqBQgrVgQ2DPsxCif2LG8JJo8ytk=w1920-h1080"],
  roast: ROAST.LIGHT,
  price: "$23.50",
  webAddress: "ethiopia-kochere-atomic",
  description: "What keeps us coming back to coffees from this region? Case-in-point: this one, with citrus acidity and spicy accents—bold flavor in an otherwise delicate cup."
},
{
  name: "House Blend",
  brand: "Atomic",
  country: "Honduras",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfC8nPTXTRIzS4JE7_JfI27sIspftkAJWzvIV0j9w77RnTZ24kRqVuC0u65mxPyT6YAwD9Zc-fXkDhMXqgfjZDbrBoa1mWnWvuJlPruYxLxbX_jkis=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdSCii_hf6j4eZ3j0khZClfZmMNACpWGZ8eDfXmh2X4zyRJ4ks_kDwnBmaM2VvqPTUz-zhHRfVHXEt00p3iBRfYID_vJSApkL8hYQ7UdTOIAPcraJc=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$18.50",
  webAddress: "house-blend",
  description: "Keep it smooth with a blend that won’t make waves. Well balanced and rich, this is uncontroversially superb coffee."
},
{
  name: "Rocketeer",
  brand: "Atomic",
  country: "Nicaragua",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHd2go-ah9ngs2IPl0tEgX1ExD1Tqh-eE3eGyM8uid368j1PVK1eeIgJ7p3shDUMBRCiyUUkoYKpd4oDeuIpW3M51-Sh3p3BQGlQlIjbXmZwRtlbva4=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfksNLHF7Dw-ttgg4a9ob3IZnTVF8YBV4ZBBVxRFnxYdFdDDmJB1frc76qCpReaNaFrQtOB3EFmOMZrKnnQ1542_biUiI6ZNDrqin7nNcF8QoIix2I=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$18.50",
  webAddress: "rocketeer",
  description: "Ground control, this coffee needs to land in everyone’s lineup. Smooth and rich, spicy with a bit of citrus—it’s just a people pleaser."
},
{
  name: "Space Cadet",
  brand: "Atomic",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdRo52UJ2PqJ0ra_Yxnivz24AJLL1E7F8YcBJh2oUcErfCIF8IqPud59qGBb-nqf9J47vHV_zOwx7L268Sdt2VjfCOUQTWFgLd9l-qE27GkfdqUkOo=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHc21ASqlo_nqDdhg4rDTCh53tmK5hrBDC6X9a_M4a5i2SfiKVgN9rgKNc7tQQsIPY9EcscE1U7ylNyR1PqroLnuJNPCjIWgfdiJlOAYlAuGLbBK0n8=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$18.50",
  webAddress: "space-cadet",
  description: "Extra smooth, extra chocolaty-sweet, and dare we say...extraterrestrial? A splash of ripe cherry juiciness makes this crowd-pleasing cup every bit as delicious hot as it is cold."
},
{
  name: "Witch City",
  brand: "Atomic",
  country: "Costa Rica",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHde0Xfm7E8Z-fL_weyY6oIh_ELhPSEVDf48KRVJpQc5LFgG8xygn1uukRe0_0G333pL-swaYrFSjyH34zS3QWP7vkGvoUq1NgdY0v5nwcxyRdXjuvg=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHf-3Zi2nPA2I2TTQ9Eu20SARypezV12Rv2cM-udvgqstroUQtQEFKAn4HGa7s6ChbWUJwzFcZCbdLO7tkBup1NpUDxeSHsmLN7RIFYwJJCdrHXyshY=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "witch-city",
  description: "For the fourth year in a row, Atomic is collaborating with Georgia Wrenn, a 12-year-old artist from Salem who creates Salem-themed artwork under her brand 'Georgia Made This'. This blend is more comforting than scary, but it'll taste delicious throughout the fall."
},
{
  name: "Brazil",
  brand: "Bean & Bean",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcPD3uTZ5MGKW247euOBZB_LBhP911xluXi3t6IQW6JVdDEyqeGdHQP-ohH-s4x9K3VeAgddhggqwr9r478IdE2ErISHdg-BqzPVP7Iu0HGIP3nrw4=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeoPUmyCEY2Klv2D9TzHd_9cwGd1-xI4gDwjpxa5fnLuXsddJ7sxAFr4Htt3plR1ThwNCvj8GSin7P-4CUYp1UQAKVg7xC7SeG-eyuckHuQHoGDZ_8=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "brazil-coffee-b&b",
  description: "Everything you could ask for from a classic Brazilian coffee, this one features a rich body and tons of fudgy sweetness - combining in a way that reminds us of dark chocolate peanut butter cups."
},
{
  name: "Costa Rica",
  brand: "Bean & Bean",
  country: "Costa Rica",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHc08r9zlqZnohvoSvEvpmh9VmwPPXI0VsINT2S2qQizM6_Y27tZqcANM_-y_YRdRs1vbFMJ7k2iutyWnHScfWwUvxQD_29XWO6ceraO0mYiv3_QUng=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeNxTDb8iic5qb0fE2U55EiTMja6FHvANtmNkRzh3aHJjRkAbsGtc9xtFK02TRVbHHtcEpZ5cn73ph6SC4CxBcWy2W_nUe1jiJkHBHrBEWRB-2b8_k=w1920-h1080"],
  roast: ROAST.LIGHT,
  price: "$23.50",
  webAddress: "costa-rica-coffee-b&b",
  description: "Unique and delicious, this tropical Costa Rican cup reminds us tiki cocktails with notes of ripe strawberry and juicy pineapple complemented by a lingering nutty sweetness."
},
{
  name: "Decaf Single Origin",
  brand: "Bean & Bean",
  country: "Mexico",
  region: "North America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfrHjtfru7MNgVk5jpdTflVG8KuPsmWnuw3HRgnrCbRATnamGFB7TqDJFbcU2JTPrnm4LXk-zML65weP4Y8cdvTOfNhtygnpSktUaP307pQvO7hPM4=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcIivvyhyo96GuSuGf-CzbQzyBQP9iRsqSHCkMnECOMynxzN71ybT2Q-V7G85sLVELCcbdGle3f10JhPhO1R-rgVjORYzqo_czrL_ouFW_foUNm25A=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "decaf-single-origin",
  description: "Velvety smooth and plenty sweet, this fabulous single origin decaf features notes of honey, apples, and caramel."
},
{
  name: "Downtown Blend",
  brand: "Bean & Bean",
  country: "Congo",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHf_pfoMJ0a-B-qTUK6G3FPrLC5EW5ExEo3yph1Db45yPcE5Mxbk19ECYiumDEAT7f-e07U-ABvCYP2AQlYDZWs9lDFuXt5E4POK3QKvfVALffSVyhI=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdWTZB3wPl4w_ffxr1Mqe_9QIGWt37QaBa6aWtwKun4Sr05XYWUCEw3mty5P12KofXVkWJRRYk6mUUB4l6DQxRadqTs5QQzApqFQto6fFIgNV3j0hw=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "downtown-blend",
  description: "Silky smooth and plenty sweet, this luxurious blend features notes of toasted nuts and dense brown sugar in addition to hints of cocoa on the finish."
},
{
  name: "Ethiopia Sidamo",
  brand: "Bean & Bean",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfJOYoEXre-lYTKyMpDnbNWpf5slN4A7qML8yvbMIR3zSK_aeGWL0hHXltZGTeQu_-WE_ZViUsN9HWMH9xQkHybViOstqTpmZMkaJRCVVqadE-TlNU=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdcQJTbMr0mefNbk6yzLD0sPMVQ18M4qbly3-asE3_oXKfh4sK-h8rPpAVtsFm4BvE61t8c1M4yKkTBJ_eIskMaVA-D3LpBgGpGcsqaplsyY4IstWc=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "ethiopia-sidamo-b&b",
  description: "This elegant washed Ethiopian coffee shines with a bouquet of floral notes and succulent peach tea sweetness."
},
{
  name: "Fancy Diner Coffee",
  brand: "Bean & Bean",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdy19jl6i-XwiS65X8UPToWZmMIJuzufYYLVfxonfb8XOBJKbK4aYn4DCJQdbEBwcByHT2J1-iBpTSmOqmm2wQRAu_-PztfgRI1z8T-tULLdxxZ6TA=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdm57z7K5iVgbygLzOJfGWuN1p3YT9A6Kmxxm5Bwxv2JkM1EP-9R-wtMJFSbWNYwd0iVmr9lqLSR35X4cwQq3DI77KE-SGUakMbSSV-x5xD6bhuiiw=w1920-h1080"],
  roast: ROAST.MEDIUM_DARK,
  price: "$18.50",
  webAddress: "fancy-diner-coffee",
  description: "If you're looking for memories of the all night fluorescent dining rooms in which you first fell in love with coffee, but made with much higher quality beans, these beans are for you."
},
{
  name: "Hawaii Kona Extra Fancy",
  brand: "Bean & Bean",
  country: "United States",
  region: "North America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHeWjKfTDnWVysINU_sMV0znTNB8hfoYFC801U3PEYVOx13dkwCjqxQUYGgTJMOYoulMMyqV1f33io-WeqpfB14Kj4Ha3lcV_2lah9vNtX5tPtPHIvw=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeneEPLGqHonBnMsMEV1aikX8KKYl9ITlMaTAzYzxRcCFkNdJn5I5KsmMElP8Uu_FAduhJz623IOtg_bbI_CEVMmDiIzGSwciGdMZUqPaIWUT5kx_M=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$18.50",
  webAddress: "hawaii-kona-extra-fancy",
  description: "This real deal Kona coffee is super smooth, with notes of brown sugar and sweet walnut balanced by gorgeous green apple acidity. 10% of proceeds go to the Hawaii Wildfire Relief Campaign."
},
{
  name: "Indonesia Sumatra",
  brand: "Bean & Bean",
  country: "Indonesia Sumatra",
  region: "Asia",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfqVwR6kPXYhNDNrW0Edr12QiVc34BS_9MCAOhHu_PzzV3TVkEU71S-JNtsSjiF3jPSbbsUfo8tWIP6gdBIP3KTmZJ2FSEQvEge-vnhHE0yJEIoexw=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfzYmQhXTuZu6JulkjnmM43XtddCkXr4EPw6nLp2ZzmcWjEtab-lCFeI_FMMUzo0GgVBI2UybcHg9rB2xhfP8P-trSSfLPMTju9cSMLSRDlDjY3sg4=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "indonesia-sumarta-b&b",
  description: "Pleasantly sweet and round, this coffee features dense notes of brown sugar, juicy cherries, and a hint of earthy cedar sweetness."
},
{
  name: "Peru Las Damas",
  brand: "Bean & Bean",
  country: "Peru",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcCMl4PIHLpNIrld6iX1iOgAMYMrv4Q290qPjxeDffTpGg7VtwxUHM24StxGeGlThGlZ0lqVyPei6Vs9AgilhhYD5nlVDWgc0tNL7LY84E3Dn_adtE=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcN-mA8aM8skbwF6Smry_bYe2i2Jj2gx6kfbHY9bZuPqcv5skiJENCHQ0A0fR5N3r8EdUcrmRh06kFrl17fi2jw7tZcI-Fa2mjiNlI3xP2-YwLrMTE=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "peru-las-damas",
  description: "A creamy body and plenty of bittersweet chocolaty richness combine with zesty orange aromatics and a hint of nutty sweetness."
},
{
  name: "Tanzania Peaberry Kilimanjaro",
  brand: "Bean & Bean",
  country: "Tanzania",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfNYS5lsh47HS9Ox-oIADahB9sovQs6bDSw8zsK30qD58sydntvrI6lZLqVTDSNNLIQ7WDUh_JHTHNhIW7GwdlL01bzcO3fOKRcaNbNB45TCdsl7Zw=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeHPGD21um2lbrEmvmYmQUzkSKIWBxjRi8unQcrpdkdYPFdptBsc2LIH9Wg2_Srj2zHAcJAR4q32LwIs07PI5a05mZsyrmyxhRHf7z3Nv7db_py3wI=w1920-h1080"],
  roast: ROAST.LIGHT,
  price: "$23.50",
  webAddress: "tanzania-peaberry-kilimanjaro",
  description: "Grown at the base of Kiliminjaro, this coffee features a rich caramel sweetness that perfectly pairs with notes of juicy green apple and zesty citrus."
},
{
  name: "El Retiro",
  brand: "Bird Rock",
  country: "Guatemala",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHeDPGGib4E_C_VomeE2YZNFCxDxrh-zwPUCRcodA2fo0uYXECGIbIkHBlovntkKw4oJRQnsr4j4K2rk0Ejr0nXJTR_kYH7G_YOEJPvDM48mVME5W6E=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdGwztR0dKo-vR0-69HomHviKCw_bhqUOpuowi04oSeGKVhdoJ2r3Y1uqXN2XqqoN4ZIJ8jc4dJX_Unr0YhX-ihOnAZe0Uk5SYUZfNqwoybFcPir7g=w1920-h1080"],
  roast: ROAST.LIGHT,
  price: "$23.50",
  webAddress: "el-retiro",
  description: "This natural process Bourbon variety from the Chimaltenango region of Guatemala tastes like ripe, dark grapes with a hint of cocoa."
},
{
  name: "El Triunfo Decaf",
  brand: "Bird Rock",
  country: "Mexico",
  region: "North America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHel7GRmb0wNEc5mQMtw43wl64WxgUQJM_WVVLAyHfOv4evbjWCXd7jvtjTDcuP4pQgZW9rYPSh67aQnRECfwJRNEfXQYfOAoSu0m5m9pKN3ISx3Kto=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdh99BFaK5mqIrBv_mCPDlb2zdtlv241AlD9atYvwv0hjZwpjUjnv8RhX7SZfyX6HDXlDgq_sF4SE9kfkr0Cyr4MWn8rUDbV42txRljiyss7EI1g8w=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "el-triunfo-decaf",
  description: "Classic and delicious, this delightful decaffeinated cup feaures notes of sweet milk chocolate, rich caramel, and syrupy molasses."
},
{
  name: "French Roast",
  brand: "Bird Rock",
  country: "Guatemala",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcsmhhWxefoa9fCXhmSHdMhkEaO5EUBmQxoGg1mi329-fOMcQJMStUXgGzLJUgTzWHuZijcvHPB27EaDRHXq1jccMOLuUCMsYr1xP9MXlaiKvunBfs=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcmKaOkz9YanAb-5nNeCKEFekr1B9ZNe9ae0xDqdp4wceZ6ELj57y8VEfg204xuyQ6NbubJ1zrM8a0B8Dc7FiAcI4EOpRJvTO4NaG4OL9HNUJ05wUg=w1920-h1080"],
  roast: ROAST.MEDIUM_DARK,
  price: "$23.50",
  webAddress: "french-roast",
  description: "The sweetness of dark chocolate and cherry gets a kiss of roastiness in this deep, rich, full-bodied cup."
},
{
  name: "Monkey Bite",
  brand: "Bird Rock",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHenwba72FKeeb51oFpKaVPW_c55Plt0i7gGmP7kgAZshEwgGx2aFrgi2WzVNmAyUoHLpwRUrZv-dHVB6BqLe5w-MZ7siEfyPWz-b5wz4NqdBIggB3Y=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcDtuNMyHhDysnmAgMOzUUwYb62kzyWlEzYVcl7YHEEk5dOQL3UtDGT3_jDHgXwUxyxqljf8FxdErwrfAApiDVRRgVPhgJvPi7pQeKb0W0VsHVmM2c=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "monkey-bite",
  description: "The sweetness of dark chocolate and cherry gets a kiss of roastiness in this deep, rich, full-bodied cup."
},
{
  name: "Pump House",
  brand: "Bird Rock",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHctzWZZyIExQx2DC3PstzhqKEObKLYdxC7CW-TXzlOEm0QxcSG5eRM1yfE21Y4Z9lHmqi6SGnKYadtERIn1P4jCnQJE1jVc_QeqPySTZpVvjwEi_Cg=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHclH9d-s3UyU1aoF6bhIQhJgfDAW-xbvJnQYf6D1u01M3Jh4VzwTPaoxoGb97gMEciNsRu2lRAtwz5Jw1gUI3JTnIVG8fGfGt7cBCUKQsciBv4lXFw=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "pump-house",
  description: "Big caramel sweetness and just a hint of fruity acidity make this coffee perfect for espresso (or really, any way you want to brew it)."
},
{
  name: "Wate Gogugu",
  brand: "Bird Rock",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfkC-TGJWMXQUqq5UZNqZvndd53iycxt2IF-_dZ7oYkwOHGs7Z6-_5ig_vQTW1Ra8Wro6EhV6jV-na4fybMUixTh8vH65ghNb5fo4xzhIIXnJxiZsY=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfcfGXSzoEnC-8reCd6Re-cxNMoLwZHxLpiVIbXYtHJg53UhEsxNdU4ixxYg_0SGbpOmY4amDjlJKhRmgdQWkM3zDdQBZ1VSvOSavxOFwubKnl7Aco=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "wate-gogugu",
  description: "Tons of floral aromatics and notes of sweet honeysuckle make this the perfect coffee for spring, complemented by delicate notes of black tea and zesty lemon."
},
{
  name: "Agua",
  brand: "Common Voice",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHf4A07R7MB_1bMbgDuVUJLq3cX7Lmuqd9qXMExGwdm4ALVJRXxBhPZXJZacdpr3JpVOFjpLsjI3_c_RrfCkKsioFuGlN4bq7eIpY0EFo4sm0XRHzDA=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcF1u0SMypdap_BqHaFhdne1GrRIqlcdODB_mnMZC0zhGyzjDaIz_KPSJxanKzIiUJs51DlMO34COU2oNRsZribCyFH-cjmHOodJvJ_IC3f82rSFVM=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$18.50",
  webAddress: "agua",
  description: "This fruity-sweet cup offers a juicy citrus acidity upfront, then balances it beautifully with a lingering nutty sweetness."
},
{
  name: "Canopy",
  brand: "Common Voice",
  country: "Columbia",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHeeMsAy_ywBQiKSZ0Croyww8tsxyVh5EUbWYvnAMzf2nZ5rJK3Q6vhkRjSEh9bXwgEekEM7r6vjM6i-JFPqvdDPQKXffzPjU5Pd9UzOSWQhfwfj_TA=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcLc8a5vvPaXLglE68uMNz-LSQJiAouXIfi6hqb7qPZCK-eO5acXrNe9988rnAVMRhuhptyNPGTByNf_grhD5Amtq899gLUh_uCfGk7LbON6iE6PT4=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$18.50",
  webAddress: "canopy",
  description: "A deep black cherry sweetness peeks through this coffee's pronounced dark chocolate and cinnamon notes."
},
{
  name: "Heirloom",
  brand: "Common Voice",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdNU8X_4ynyOPEEE7rj3md0zQXBcBCPxAI06i0FxqChvcyBLEw81auqsCDSvkegAOGHRxdTJWKhGeutLxm23w6GaCqYWheMiUfgzz-jQ2zl51-z27E=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHcnkGKqSAmgnZj8CddW0F_x_2dnkPPvaqbs_d0YKPbdOEl9ciKDzN2jD7w7On7aeDOzoB0E6TakDAXwB2G98kWqd7Gbs170jrA2xb0hMWNXAXc8uuc=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$18.50",
  webAddress: "heirloom",
  description: "Chocolate and almond butter sweetness for days - this cup offers that classic candy bar profile, with a hint of juicy tangerine acidity."
},
{
  name: "Sunbeam",
  brand: "Common Voice",
  country: "Honduras",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdLB3D0676IqYBsjz_bmFby7wVXVh9dhiX88Bn1Yk6afVKXWV0aTuWwqHefCvgDOsfQHCZ4T8DIoPR7D0TgsLtvHld86vOxosbA_oi8pkJ-M6i8HrE=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeK1jxPWAFS6qZTRlNHxrmafihvNeoA2bxjQOY1cP6GDqlGPA0z3QIr5m968Z2w1x37AD8Lwmbng3OuEm-aemstIo5VUnBtthh3b7QlJlJWfFDC1QA=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$18.50",
  webAddress: "sunbeam",
  description: "As bright and joyful as its namesake, Sunbeam delivers a shining citrusy acidity alongside a gentle chocolate and roasted almond sweetness."
},
{
  name: "Terra",
  brand: "Common Voice",
  country: "Mexico",
  region: "North America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHez-Lai9GO2-tuO6-ANAUX31962S6csGtVaLUE1y-TrJYfxnjf_ZlcnQlAESnF8iX1TYnOt0rdBf8QiXRMZbXElobxdd6htnZsO3VLjp03i8c7P1uM=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdfWCceafWIA8lYb0SlMCU4DCT3LEvDI_vddhWnbonSPdiS6qS4-ECuOTU543nGeHUH_keuCsWkv0SOyEp-u2l5RrtPxA6weoxjS23s6TJQqK5ZY3A=w1920-h1080"],
  roast: ROAST.DARK,
  price: "$18.50",
  webAddress: "terra",
  description: "Terra's deep, dark chocolaty sweetness and kiss of roastiness pair beautifully with your milk of choice - its gentle orange acidity makes it just as delicious black."
},
{
  name: "Karmadillo Bold Espresso Blend",
  brand: "Cuvee",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHd9bwFBfGqyQH9BBn4yD438VB2x3hn2mhZPNBL-TCBnm9KDAo2RmtAJLzQwFEtBZQ5tbqNrS1_2U-zGGoLPNVVgKTnG29TSXw-gudGYfPsFrmja57I=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdu6x7bLzv9bgbFM4mHx5IOth42h7ZHkNgfpkO_eZD6O29iej6FUMTgYa8D2ot61yFL0l_P4JFgPExjsg8l202TZ4DbmvoGubNuzpdW9W8ZHVUkfFA=w1920-h1080"],
  roast: ROAST.MEDIUM_DARK,
  price: "$23.50",
  webAddress: "karmadilo-bold-espresso-blend",
  description: "For those among us who live la vida mocha: here's your go-to. With incredible depth and chocolaty sweetness, this one packs a wallop you won't soon forget."
},
{
  name: "Ecuador Hacienda La Papaya",
  brand: "Dune",
  country: "Ecuador",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfBK_rRmOX15ED2jyYWnKuUyAtMjI-BGixisoMX9DSqONw-cY-DPC-SXpRbxg0SIplKX45sFyvbijkpFg0_siEzWvIMepjYFqcsX88GjuK--eJxl5U=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfBH3BaY0tCSkrk8hrTRzXJMeNO37Nu4t-AdeGkOoXxYzz4RShVqi_Hkb0KkHEHxzKD0pPYNnMem-NZZPfXAkIRy468E-ax-5YFG4wQNR5_r7ktzxo=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "ecuador-hacienda-la-papaya",
  description: "From one of the most oft-praised farms in specialty coffee, experience a cup filled with a special combination of fresh raspberry flavor and floral aromas."
},
{
  name: "Ethiopia Yaye Natural",
  brand: "Dune",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHd8pl3U5rS0kV4lL9mjOHNEOvq7TUDkSkktn4TO-buvSbO1Ugn6SQmZ_G6pGDwLoxcXpYreAzrtcDb_b8eywyd-AiTqcqFgi_ItobwOz_e2QSWfsJE=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHevf0OUP1bBQSNR5A8QgQhTbqaFzxJ1NKKvbAA9gZGoYIqAk5-XIWHwVuaN2TK8pstpx_kV7H6DY0zmx7nhekDYGtdD44NwWJflyVMDshHQoOfNMyI=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "ethiopia-yaye-natural",
  description: "Lush, ripe red strawberries star in this juicy natural, featuring intense flavors of black tea and a deep plum sweetness."
},
{
  name: "Guatemala Martin Lopez Alvarado",
  brand: "Dune",
  country: "Guatemala",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcgpX2CoS9O8aV50quMfFN36UAluU1tiBxY4pDlvjYRANL8qXL0SYApdWlWVEdAbpKzxduvL0yNcgjCfdhff4bkT7R1HaKJEh9ffsUXDx14LkpTvPs=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHczYu1LlBk90I5YhL18PFpTmuzL5NwLFpR5_3UB5c7mw4Cx5ssS3bljJfM4X2lTRKGq22N8coi2C4OJdjLqCJzPvZ-DvA_woerZ4Ap5baBrtP6tV9M=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "guatemala-martin-lopez-alvarado",
  description: "This late-summer gem features lovely fruit notes like nectarine and grapefruit, with accents of baking spice for good measure."
},
{
  name: "Honduras Pablo Cruz",
  brand: "Dune",
  country: "Honduras",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdb4EfpkFm1LGfYey28NlmfvMRcaPClHKQUtvHDiXhtZ98suybDFpOvJCIYX9aO0CGIcpiH2AaoK7Bz3VfTDhq3uUOHwXnzypYAudJHDxGzkYcSBxg=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfZumBOq9ZK5SIhIFb4-wyDSU-YE3Xw21CoApzI_b8XRjtE30bXkH4s9EILnqk8b_8LNl_u_P-DDjx0Mk1J6-7lZ-ovQvfNeCTteRroJvamjxOPyLk=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "honduras-pablo-cruz",
  description: "Balanced and delicious, this Honduran coffee features crisp and lingering notes of green apple, complemented by a rich sweetness and creamy notes of toasted nuts."
},
{
  name: "House Blend",
  brand: "Dune",
  country: "Colombia",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHezyyoWI33XvrFQvGVof9oFwDy3NY8vYB6RLch9QnAKiwFzYeNRohC3L3oOdrdQr3iFIc0JPNdlxakXjXxpwpOgHRhKmJNfn_oXWkhLX8B2ZeQEp9o=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdULygwL5alFrbCuCApdO1oBrR8A8Dg65h9BDt8lqVKKDrgR89fwqOBIBRbtgtd9w9LvfvcbNreoubwzyPcFV8MT4psq0jj_W_9ynAcOkfZjuajbdY=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "house-blend-dune",
  description: "This excellently executed house blend is an absolute crowd-pleaser with tons of sweetness, a velvety smooth body, and subtle hints of fresh fruit."
},
{
  name: "Presidio Decaf",
  brand: "Dune",
  country: "Colombia",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHchEPtW2kQRBPMBCt64O82BYMC7nHNDkwa3oXX9yOus79nJNOR9qxWjk9FNhbulz2wDJ2kK5Djvg8PduIsEVtFfZNEmKHOQIdchcxjeYOeY-8uwoMg=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHedN1d26D2EqNqv-XyqaHyknTvzPMnpMcZIGh7sxgdGU-Kzngjh2vmJXdiKhtDjwIjfcMSJnPOr4WBCvf3u218UbrhHU5Xjch-d8p-RMTQHgm-cMBM=w1920-h10800"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "presidio-decaf",
  description: "Caffeine-free, flavor-full. Sums up this easy-to-love decaf that's plenty sweet with notes of juicy cherry and bright grapefruit."
},
{
  name: "Santarossa Blend",
  brand: "Dune",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHe6ijAOQSS7_j2jkZqRJus15JBWvbObWkJaLN3uc_63lIJ8H5G2BYequR-EAiIFyCLFCMykcAatnhwdrJB-PhFwetWEVQgyxAPGoqbM22CQ0DWu9mI=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdLqsRlKqLSQzTt10mB4LcVCAV4ATN8AApE2EvFNmNT9M3B-g2ULywySOQw_rdwNzuEHhDjxH7t_bFRVdNKV4V2XWc7nuCi2igG1elXTLN_FTmc3lk=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "santarossa-blend",
  description: "Sweet, decadent, and just plain tasty - this blend features syrupy caramel sweetness, with cozy notes of toasted nuts and rich cocoa."
},
{
  name: "Zip Zinger",
  brand: "Dune",
  country: "Colombia",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHe68OU4HeHEqKMUh0gFlI7spIzv8KTdY-VvMjqd4Xmu-V-rI16cXgYmrUThrhsWpU3sKWcJA6QQ14kQffITtkAc9TgCrAUnnqbe7NDmwRvdRY6WqzA=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHePrqMaza6OX7yqFxOmw_ufa7LS8OpimecHqbmn1rOv3TKeZRkS9vdP09PtbV6t6Wd6YaqXYX_4fHTwjna2XpwbBO0XSH8hdadfJuxT6BJWeIhD0Sw=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "zip-zinger",
  description: "This versatile blend likes to mix it up. Whether as a sweet and fruity drip coffee or a richer and more chocolaty espresso this coffee is just plain delicious."
},
{
  name: "Dipsea Espresso",
  brand: "Equator",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcWXPv1qgESPPnA8ycIyPim9vxKalxmoNgEfex6M7GoxJjFCM6nbRp0S2kVdNjXFI9BEt9UpUga7HL9DlRF6qTDtbAMCOl2EGEYKNbyvbt9HLwRk64=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfMCxWVH8Nw0jim5q_sUwtLB4Xu9FPqSxq09po16xoW0RQrnGkt6Y4DBXsN4FN_sfqlQggep8VewW-IbbBZWNIJlBZfUsXfTiDwHsrUWdre6JYNl6g=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "dipsea-espresso",
  description: "Brazilian coffees often make up the base of an espresso blend, but this coffee, named after a hiking trail in Marin County, proves they can more than stand on their own in straight shots or with milk."
},
{
  name: "Ethiopia Ardi Natural",
  brand: "Equator",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfSMkSdCkO-i0bDQZ9_sN9GwdtHvTg7AAhTh4Bs0qVnh6vSZ9BKeLfzh-6a0H3y6_S8hzhdeEQpnFWUwyFFriaSolA4nR9y4bZcLD8veQeCGEDfpMY=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeeUZyXKBxNGNFcu7h1w9aWUb87MmwVyc8XLifzJTnG6PCvwTF_Rj8aMGwJBHYdeSH5gae2tbbsModFpRQvXmrdoZ1aC0WKCiSOOdIEHpctEqFVR64=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "ethiopia-ardi-natural-equator",
  description: "Smooth, fruity and sweet, with notes of vanilla, lavender and meyer lemon. This naturally processed coffee may change your whole perception of what coffee can be."
},
{
  name: "Eye Of The Tiger Espresso",
  brand: "Equator",
  country: "Honduras",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHf8byNU4sZRLxTuiv7IAqHy-zB79EsTMTvXwDUQ3HvkrfPceG6Rd6iOVC5mxPQgA9FmUhGZSTOrSIIgeGDADHKg_Kg1Lmdf8bDcNzXvb2_9epomNqM=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeRFtItNLqXkj-HYxg8ADm-aA10SaB4HRuIb5gwh5kATZx97SGU4tUZxHEg_OYv-BtDmpmuGv6KWKJc5IKNaQIT-aFgAEDoWRmumTN8o6MdE0dW0Ok=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "eye-of-tiger-espresso",
  description: "Juicy cherry acidity paired with incredible chocolaty depth and nutty sweetness will have you running up and down flights of stairs in the blink of an eye."
},
{
  name: "Nicaragua Las Hermanas Fair Trade",
  brand: "Equator",
  country: "Nicaragua",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHd3s8UOFkfYCdhn19zsTOtCImWLVWzmt5lCY2qNAEivY_KHe2Xs07yiiPzwNoMw5sjpY2S8rLfp4ey4rFK2rxSEHOhWrxuaHO4XB4lFf7vLEP6U1E4=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHe2XQVvzThScbGDYWNWnwYCF5qCtHau6e4401OTho3KD8Ada5X2Wa5Ym8_orkmZL1wK33kCEl4BEQ777QQgi5ydkQs0LJzo-qtwcAIZM5MDY7aFYno=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "nicaragua-las-hermanas-fair-trade",
  description: "This lot from the women of the SOPPEXCCA Co-op in the Jinotega region of Nicaragua brings together ripe plum and tangerine sweetness with an intriguing note of cedar in the background."
},
{
  name: "Nicaragua Sacaclí",
  brand: "Equator",
  country: "Nicaragua",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfg_pBD5mGJ13TmSNEMvE3WEnyHFct5jGwVdZ_gaqYIAUoNhhLWGRtERN-iGb5wlQkw4_UoP6uAi0tvH11Erf34cCkdpHg6UMiYYUM5D9kjt161UjQ=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHdupMGXAghBHGneCmY3OMa0xWCSR5NLloI09t-71lOZ0EVPSHm0AbmVzRRkfWTyGfTH1SWJsSn00-0Q3pldaQ_krXp7RawAz8CQR1AnY2oZY-1Uumc=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "nicaragua-sacacli-equator",
  description: "This Nicaraguan coffee is the first to receive a regenerative agriculture certification and tastes fantastic to boot! We're tasting a delightful balance of crisp and juicy notes of green apple with plenty of creamy sweetness that reminds us of toasted nuts and well-made chocolate."
},
{
  name: "Prime Meridian",
  brand: "Equator",
  country: "Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHd8jKYLdS-ITWX5i1xOubC3kaUg1nuTUpCr79m-wQTqQeCo68Tb-w6WQS6nkPlD9z1K-ldvAoZPQHvPzePOjDibO0J_HxbDHTUEFoVej8BMeQHI37A=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHc6KPGLyzvOO0-uoAzwWBykncRBcfeh-M2dvXnpDl8OiImqCrma9fXgcNpOATbsDkSsm-4wrM_QJUIon5r7sdWbYMp404bYuzHRsSZIybg7G2PKc3A=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "prime-meridian",
  description: "Big bodied and plenty sweet, this comforting cup features notes of dark chocolate and roasted walnuts alongside a dark caramel sweetness."
},
{
  name: "Sumatra Queen Ketiara",
  brand: "Equator",
  country: "Indonesia",
  region: "Asia",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfzuN_r5H5WDHkcCPZWMFMndrNCkx_yxF3T-i-YEOarqY0xtBmQf_pHLDMTkQU2_CPotXamRlqZXXbj1mjVfX0-p7D-f_iCCF9DjDVMVi0a-TNH6z4=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHd1XT5BxTbe7ybLCfN72ylu3QB8C-loyaRN5uYStBaKznZi-AeZf5Wq_v5p-Sp6STbgxnEUi6SmNIlOZmGpX4IlE2PTumCueGVDj5wkFEM-cC9W384=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "sumatra-queen-ketiara",
  description: "Sumatran coffees are known for their earthiness: this lot, sourced exclusively from women farmers, transforms that trademark note into a sweet tobacco, accented by baking spice and chocolate."
},
{
  name: "Alberto Mamani",
  brand: "Feast",
  country: "Panama",
  region: "Central America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHeJKFxEnVqxf10Bb9wX62iCknw3QKpDOF7D1RvKeFay77ILvsqRFnIDt9qGYhCYS788sYi-M0cVZ96o6d8NQ2DG3ozYlUaJDXZpvW1rJmQh2LxOwMc=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHfMJwYqNj5gZ3mHxSFn7NcGiiyVJW31XfUm2p_8EJ64cQwoGICchtMNCeMB1brNYBH09MeEiQjtiMV9BK9dRzYpldTgMSDw730SXW_wvHSBJwU0jZs=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "alberto-mamani",
  description: "From the famously steep cliffs of Bolivia: this comforting coffee that reminds us of the flavors of apple pie."
},
{
  name: "Huellas",
  brand: "Feast",
  country: "Peru",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHdYCBkxRfLmybfz0iLI4WIK3EOPlO7mh1kdal4tHRWMC5k2QTQRUDnjyGnQSyf8hv71Xarkf3G7pY5SnTBw8ng71JP8o9qp56CFOAQ5eAOAwRGOF-A=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHeKis2Zc_Rxag_p8vW0FBhyDAQfuM_6ZcX92N4byxFrCeqF0vzSkJQcf6bLgEkEnx1kfCUHlO-D1KvIiXndd4siDoK7GUCVS827Wm8zO3LFLKBCHB0=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "huellas",
  description: "Complex aromatics, a big body and tons of flavor–this coffee, from 14 small family farms in Peru, really has it all."
},
{
  name: "Milk & Honey Blend",
  brand: "Feast",
  country: "Ethiopia",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHexWLnWa27XGegJxtLAaCypcFtlyg702q8SLDxj6lcB-_lgBhNnG79j0ksuQSRnQjPPKLGzy0OChlL_IgneWm_6mAD9l649aCiGGATOeWQKvLYW-50=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHc_o5bzUclLxvXAJvT7pGStytVytyIvd1rWbisiW_wpCg8damUUa2y2r6_osyzlEo1dnxCiuN2hjww-X1vNg2ia8pKJfMaEPTm5L56Vc2aKUmFAhYc=w1920-h1080"],
  roast: ROAST.MEDIUM_DARK,
  price: "$23.50",
  webAddress: "milk-honey-blend",
  description: "With notes of bittersweet caramel, creamy milk chocolate, and a rich, roasty body - this luxurious blend lives up to its name."
},
{
  name: "Njowa",
  brand: "Feast",
  country: "Kenya",
  region: "Africa",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHcT4kzJaPFchQckMwrTxenSaiyDrBpJ9QRaIqN4gENgiryK9axK4gyi8ITRvyJtBSoqHSlsmDUkmkXhvv5HJgqxQId5zkQBZGYCxKMMuE3ec_LTcys=w1920-h1080","https://lh3.googleusercontent.com/pw/ADCreHe4yVoc6_rZceGLAAZDBvDtitRYNG3IgIfuBRLC_-Q-3AOVNSU4q982DHYHDqTIwH0w6pqOx_cr3oudLtfhFhMVHiMfxVGpw2EDXflzICiEIIP_4so=w1920-h1080"],
  roast: ROAST.LIGHT_MEDIUM,
  price: "$23.50",
  webAddress: "njowa",
  description: "Funky blood orange acidity makes this big-bodied Kenya a unique treat."
},
{
  name: "Power & Glory Blend",
  brand: "Feast",
  country:"Colombia",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHewQ5Yxc2L7uY-d2Bh4i2oiViJRjpro8hwx7SFDRPle2my0wDC0zH8DyOmlWFY61H3eJ0yzXCFJY5VjH4pzSp4X9qDU1hf48Db2lxVL-ZeNlqPbg6E=w1920-h1080", "https://lh3.googleusercontent.com/pw/ADCreHcLYOtnYeN-JsEdTZuOjzm9mz-_zLqOVq8nxLI7SqH_u9yuzMuKRRrv41GuMQv7ESDC3PtqN8pZxNP2DqBV22b9wvlso20kMsM112aYh224dwf3P_E=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$23.50",
  webAddress: "power-glory-blend",
  description: "Feel the power of hazelnutty sweetness and a hefty body meet the glory of citrus aromatics and notes of fresh fruit."
},
{
  name: "Good Vibes",
  brand: "Greater Goods",
  country:"Brazil",
  region: "South America",
  image: ["https://lh3.googleusercontent.com/pw/ADCreHfbfgtwA0okW4ymmX1KmJNm8Qa7vj4oLDrmw983i1Bj2bH5pF2tnomHHxDu6G0YrSztVBsI2GJaKjaRNWrw8KPOmwBxeLs3IqEJmjGMpv2MnPt17jU=w1920-h1080", "https://lh3.googleusercontent.com/pw/ADCreHfWwbkdCbP3xka2mdqKBNS4n6hvADfWL-Z75W6E4s6Hi6RpQPUEm-mgLDuaQLr4AEqGeMfyOCuAeKlbl35E43rnKP2slxviwcVO4YEVRlcuGMW5YjQ=w1920-h1080"],
  roast: ROAST.MEDIUM,
  price: "$18.50",
  webAddress: "good-vibes",
  description: "A really complex and clean natural Brazil, this appropriately named coffee tastes like cocoa and peanut butter with a big and luxuriously smooth body."
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},
{
  name: "",
  brand: "",
  country:"",
  region: "",
  image: ["", ""],
  roast: ROAST,
  price: "",
  webAddress: "",
  description: ""
},


]