const reviews = [
	{
		first_name: "John",
		last_name: "Doe",
		text: "This Black Apple Espresso is amazing!",
		rating: 4,
		coffee_id: 1,
		user_id: 3,
	},
	{
		first_name: "Jane",
		last_name: "Smith",
		text: "Smooth and rich taste, my new favorite! Loving this Black Apple Espresso!",
		rating: 5,
		coffee_id: 1,
		user_id: 2,
	},
	{
		first_name: "Bob",
		last_name: "Johnson",
		text: "Decent coffee, could be stronger. Black Apple Espresso gets a 3.0 from me.",
		rating: 3,
		coffee_id: 1,
		user_id: 1,
	},
	{
		first_name: "Alice",
		last_name: "Williams",
		text: "Great coffee! Really enjoyed the flavor. Cabot Street is my favorite!",
		rating: 4,
		coffee_id: 2,
		user_id: 3,
	},
	{
		first_name: "Charlie",
		last_name: "Brown",
		text: "Good balance of flavors. Rocketeer deserves a 3.5 from me.",
		rating: 3.5,
		coffee_id: 2,
		user_id: 1,
	},
	{
		first_name: "Eva",
		last_name: "Miller",
		text: "Could be bolder, but still enjoyable. Sumatra Kerinci is my choice!",
		rating: 3,
		coffee_id: 2,
		user_id: 4,
	},
	{
		first_name: "David",
		last_name: "Clark",
		text: "Smooth and satisfying. Black Velvet is a winner!",
		rating: 4.5,
		coffee_id: 3,
		user_id: 2,
	},
	{
		first_name: "Grace",
		last_name: "Taylor",
		text: "Bold and flavorful. Cabot Street is a classic!",
		rating: 4,
		coffee_id: 3,
		user_id: 5,
	},
	{
		first_name: "Frank",
		last_name: "Anderson",
		text: "Decent coffee, enjoyed the aroma. Diesel is a solid choice.",
		rating: 3.5,
		coffee_id: 3,
		user_id: 1,
	},
	{
		first_name: "Olivia",
		last_name: "Moore",
		text: "Smooth and rich taste, my new favorite! Hawaii Kona Extra Fancy is top-notch!",
		rating: 5,
		coffee_id: 4,
		user_id: 3,
	},
	{
		first_name: "John",
		last_name: "Doe",
		text: "Good balance of flavors. Indonesia Sumatra is a delightful choice!",
		rating: 4,
		coffee_id: 4,
		user_id: 1,
	},
	{
		first_name: "Jane",
		last_name: "Smith",
		text: "Could be bolder, but still enjoyable. Peru Las Damas is a nice surprise!",
		rating: 3.5,
		coffee_id: 4,
		user_id: 2,
	},
	{
		first_name: "Bob",
		last_name: "Johnson",
		text: "Decent coffee, enjoyed the aroma. Tanzania Peaberry Kilimanjaro is a solid choice.",
		rating: 3.5,
		coffee_id: 5,
		user_id: 4,
	},
	{
		first_name: "Alice",
		last_name: "Williams",
		text: "Smooth and satisfying. El Retiro is a winner!",
		rating: 4.5,
		coffee_id: 5,
		user_id: 3,
	},
	{
		first_name: "Charlie",
		last_name: "Brown",
		text: "Bold and flavorful. El Triunfo Decaf is a classic!",
		rating: 4,
		coffee_id: 5,
		user_id: 5,
	},
	{
		first_name: "Eva",
		last_name: "Miller",
		text: "Smooth and rich taste, my new favorite! French Roast is top-notch!",
		rating: 5,
		coffee_id: 6,
		user_id: 2,
	},
	{
		first_name: "David",
		last_name: "Clark",
		text: "Good balance of flavors. Monkey Bite is a delightful choice!",
		rating: 4,
		coffee_id: 6,
		user_id: 1,
	},
	{
		first_name: "Grace",
		last_name: "Taylor",
		text: "Could be bolder, but still enjoyable. Pump House is a nice surprise!",
		rating: 3.5,
		coffee_id: 6,
		user_id: 3,
	},
	{
		first_name: "Frank",
		last_name: "Anderson",
		text: "Decent coffee, enjoyed the aroma. Wate Gogugu is a solid choice.",
		rating: 3.5,
		coffee_id: 7,
		user_id: 4,
	},
	{
		first_name: "Olivia",
		last_name: "Moore",
		text: "Smooth and satisfying. Agua is a winner!",
		rating: 4.5,
		coffee_id: 7,
		user_id: 3,
	},
	{
		first_name: "John",
		last_name: "Doe",
		text: "Bold and flavorful. Canopy is a classic!",
		rating: 4,
		coffee_id: 7,
		user_id: 1,
	},
	{
		first_name: "Jane",
		last_name: "Smith",
		text: "Smooth and rich taste, my new favorite! Heirloom is top-notch!",
		rating: 5,
		coffee_id: 8,
		user_id: 2,
	},
	{
		first_name: "Bob",
		last_name: "Johnson",
		text: "Good balance of flavors. Sunbeam is a delightful choice!",
		rating: 4,
		coffee_id: 8,
		user_id: 1,
	},
	{
		first_name: "Alice",
		last_name: "Williams",
		text: "Could be bolder, but still enjoyable. Terra is a nice surprise!",
		rating: 3.5,
		coffee_id: 8,
		user_id: 4,
	},
	{
		first_name: "Charlie",
		last_name: "Brown",
		text: "Decent coffee, enjoyed the aroma. Karmadillo Bold Espresso Blend is a solid choice.",
		rating: 3.5,
		coffee_id: 9,
		user_id: 5,
	},
	{
		first_name: "Eva",
		last_name: "Miller",
		text: "Smooth and satisfying. West Pole is a winner!",
		rating: 4.5,
		coffee_id: 9,
		user_id: 2,
	},
	{
		first_name: "David",
		last_name: "Clark",
		text: "Bold and flavorful. Ecuador Hacienda La Papaya is a classic!",
		rating: 4,
		coffee_id: 9,
		user_id: 3,
	},
	{
		first_name: "Grace",
		last_name: "Taylor",
		text: "Smooth and rich taste, my new favorite! Ethiopia Yaye Natural is top-notch!",
		rating: 5,
		coffee_id: 10,
		user_id: 1,
	},
	{
		first_name: "Frank",
		last_name: "Anderson",
		text: "Good balance of flavors. Guatemala Martin Lopez Alvarado is a delightful choice!",
		rating: 4,
		coffee_id: 10,
		user_id: 4,
	},
	{
		first_name: "Olivia",
		last_name: "Moore",
		text: "Could be bolder, but still enjoyable. Honduras Pablo Cruz is a nice surprise!",
		rating: 3.5,
		coffee_id: 10,
		user_id: 5,
	},
	{
		first_name: "John",
		last_name: "Doe",
		text: "Decent coffee, enjoyed the aroma. House Blend is a solid choice.",
		rating: 3.5,
		coffee_id: 11,
		user_id: 3,
	},
	{
		first_name: "Jane",
		last_name: "Smith",
		text: "Smooth and satisfying. Presidio Decaf is a winner!",
		rating: 4.5,
		coffee_id: 11,
		user_id: 1,
	},
	{
		first_name: "Bob",
		last_name: "Johnson",
		text: "Bold and flavorful. Santarossa Blend is a classic!",
		rating: 4,
		coffee_id: 11,
		user_id: 2,
	},
	{
		first_name: "Alice",
		last_name: "Williams",
		text: "Smooth and rich taste, my new favorite! Zip Zinger is top-notch!",
		rating: 5,
		coffee_id: 12,
		user_id: 4,
	},
	{
		first_name: "Charlie",
		last_name: "Brown",
		text: "Good balance of flavors. Dipsea Espresso is a delightful choice!",
		rating: 4,
		coffee_id: 12,
		user_id: 1,
	},
	{
		first_name: "Eva",
		last_name: "Miller",
		text: "Could be bolder, but still enjoyable. Ethiopia Ardi Natural is a nice surprise!",
		rating: 3.5,
		coffee_id: 12,
		user_id: 5,
	},
	{
		first_name: "David",
		last_name: "Clark",
		text: "Decent coffee, enjoyed the aroma. Eye Of The Tiger Espresso is a solid choice.",
		rating: 3.5,
		coffee_id: 13,
		user_id: 3,
	},
	{
		first_name: "Grace",
		last_name: "Taylor",
		text: "Smooth and satisfying. Nicaragua Las Hermanas Fair Trade is a winner!",
		rating: 4.5,
		coffee_id: 13,
		user_id: 2,
	},
	{
		first_name: "Frank",
		last_name: "Anderson",
		text: "Bold and flavorful. Nicaragua Sacaclí is a classic!",
		rating: 4,
		coffee_id: 13,
		user_id: 1,
	},
	{
		first_name: "Olivia",
		last_name: "Moore",
		text: "Smooth and rich taste, my new favorite! Prime Meridian is top-notch!",
		rating: 5,
		coffee_id: 14,
		user_id: 4,
	},
	{
		first_name: "John",
		last_name: "Doe",
		text: "Good balance of flavors. Sumatra Queen Ketiara is a delightful choice!",
		rating: 4,
		coffee_id: 14,
		user_id: 1,
	},
	{
		first_name: "Jane",
		last_name: "Smith",
		text: "Could be bolder, but still enjoyable. Alberto Mamani is a nice surprise!",
		rating: 3.5,
		coffee_id: 14,
		user_id: 3,
	},
	{
		first_name: "Bob",
		last_name: "Johnson",
		text: "Decent coffee, enjoyed the aroma. Huellas is a solid choice.",
		rating: 3.5,
		coffee_id: 15,
		user_id: 5,
	},
	{
		first_name: "Alice",
		last_name: "Williams",
		text: "Smooth and satisfying. Milk & Honey Blend is a winner!",
		rating: 4.5,
		coffee_id: 15,
		user_id: 2,
	},
	{
		first_name: "Charlie",
		last_name: "Brown",
		text: "Bold and flavorful. Njowa is a classic!",
		rating: 4,
		coffee_id: 15,
		user_id: 4,
	},
	{
		first_name: "Eva",
		last_name: "Miller",
		text: "Smooth and rich taste, my new favorite! Power & Glory Blend is top-notch!",
		rating: 5,
		coffee_id: 16,
		user_id: 3,
	},
	{
		first_name: "David",
		last_name: "Clark",
		text: "Good balance of flavors. Good Vibes is a delightful choice!",
		rating: 4,
		coffee_id: 16,
		user_id: 1,
	},
  {
    first_name: "Sophia",
    last_name: "Martin",
    text: "Bella Vista has a delightful flavor! Smooth and satisfying.",
    rating: 4.2,
    coffee_id: 17,
    user_id: 3,
  },
  {
    first_name: "Liam",
    last_name: "Garcia",
    text: "Excellent balance in Bunum Wo Estate Peaberry. Truly impressed!",
    rating: 4.8,
    coffee_id: 17,
    user_id: 4,
  },
  {
    first_name: "Ava",
    last_name: "Hernandez",
    text: "Nebula is a unique experience! Love the aroma and rich taste.",
    rating: 4.5,
    coffee_id: 17,
    user_id: 5,
  },
  {
    first_name: "Jackson",
    last_name: "Anderson",
    text: "Yummy Decaf is surprisingly delicious! A decaf with great flavor.",
    rating: 4.0,
    coffee_id: 18,
    user_id: 1,
  },
  {
    first_name: "Emma",
    last_name: "Jones",
    text: "Beowulf Blend is a bold and powerful choice. Love the intensity!",
    rating: 4.6,
    coffee_id: 18,
    user_id: 2,
  },
  {
    first_name: "Oliver",
    last_name: "Harrison",
    text: "City Blend is a well-balanced coffee. Enjoying it every morning.",
    rating: 3.9,
    coffee_id: 18,
    user_id: 3,
  },
  {
    first_name: "Sophia",
    last_name: "Martin",
    text: "Tasty and vibrant! Nebula is a delightful choice.",
    rating: 4.3,
    coffee_id: 19,
    user_id: 3,
  },
  {
    first_name: "Liam",
    last_name: "Garcia",
    text: "Yummy Decaf is a pleasant surprise. Rich flavor without the caffeine!",
    rating: 4.5,
    coffee_id: 19,
    user_id: 4,
  },
  {
    first_name: "Ava",
    last_name: "Hernandez",
    text: "Bunum Wo Estate Peaberry is a smooth and balanced coffee. Enjoying every sip!",
    rating: 4.7,
    coffee_id: 19,
    user_id: 5,
  },
  // Reviews for coffee_id 20
  {
    first_name: "Jackson",
    last_name: "Anderson",
    text: "Smooth and mellow! Beowulf Blend is perfect for a relaxing evening.",
    rating: 4.2,
    coffee_id: 20,
    user_id: 1,
  },
  {
    first_name: "Emma",
    last_name: "Jones",
    text: "City Blend is my daily go-to coffee. Consistent and enjoyable.",
    rating: 4.0,
    coffee_id: 20,
    user_id: 2,
  },
  {
    first_name: "Oliver",
    last_name: "Harrison",
    text: "Italian Roast is bold and intense. Great for kickstarting the day!",
    rating: 4.5,
    coffee_id: 20,
    user_id: 3,
  },
  // Continue for coffee_id's 21 through 30
  {
    first_name: "Sophia",
    last_name: "Martin",
    text: "Colombian is a classic choice. Rich and flavorful!",
    rating: 4.0,
    coffee_id: 21,
    user_id: 3,
  },
  {
    first_name: "Liam",
    last_name: "Garcia",
    text: "Costa Rica La Minita is a smooth and bright coffee. Great for a morning pick-me-up.",
    rating: 4.3,
    coffee_id: 21,
    user_id: 4,
  },
  {
    first_name: "Ava",
    last_name: "Hernandez",
    text: "Italian Roast has a bold and intense flavor. Perfect for espresso enthusiasts!",
    rating: 4.8,
    coffee_id: 21,
    user_id: 5,
  },
  {
    first_name: "Jackson",
    last_name: "Anderson",
    text: "Oren's Special Blend is a well-crafted coffee. I give it a solid 4.0.",
    rating: 4.0,
    coffee_id: 22,
    user_id: 1,
  },
  {
    first_name: "Emma",
    last_name: "Jones",
    text: "East Coast is a well-balanced blend. Enjoyable for any coffee lover.",
    rating: 3.9,
    coffee_id: 22,
    user_id: 2,
  },
  {
    first_name: "Oliver",
    last_name: "Harrison",
    text: "Finca La Amistad has a unique and rich taste. Definitely worth trying!",
    rating: 4.2,
    coffee_id: 22,
    user_id: 3,
  },
  {
    first_name: "Sophia",
    last_name: "Martin",
    text: "Isreal Salazar is a smooth and flavorful coffee. Highly recommended!",
    rating: 4.7,
    coffee_id: 23,
    user_id: 4,
  },
  {
    first_name: "Liam",
    last_name: "Garcia",
    text: "Mejor is a top-notch coffee. Rich and satisfying!",
    rating: 4.5,
    coffee_id: 23,
    user_id: 5,
  },
  {
    first_name: "Ava",
    last_name: "Hernandez",
    text: "Dark Thunder is bold and intense. A perfect choice for espresso lovers!",
    rating: 4.6,
    coffee_id: 23,
    user_id: 1,
  },
  {
    first_name: "Jackson",
    last_name: "Anderson",
    text: "Yummy Decaf is surprisingly tasty! Perfect for late-night sipping.",
    rating: 4.3,
    coffee_id: 24,
    user_id: 2,
  },
  {
    first_name: "Emma",
    last_name: "Jones",
    text: "Beowulf Blend is bold and powerful. A great choice for espresso lovers.",
    rating: 4.5,
    coffee_id: 24,
    user_id: 3,
  },
  {
    first_name: "Oliver",
    last_name: "Harrison",
    text: "City Blend is a well-balanced coffee. Enjoying it every morning.",
    rating: 4.2,
    coffee_id: 24,
    user_id: 4,
  },
  {
    first_name: "Sophia",
    last_name: "Martin",
    text: "Colombian is a classic choice. Rich and flavorful!",
    rating: 4.0,
    coffee_id: 25,
    user_id: 5,
  },
  {
    first_name: "Liam",
    last_name: "Garcia",
    text: "Costa Rica La Minita is a smooth and bright coffee. Great for a morning pick-me-up.",
    rating: 4.3,
    coffee_id: 25,
    user_id: 1,
  },
  {
    first_name: "Ava",
    last_name: "Hernandez",
    text: "Italian Roast has a bold and intense flavor. Perfect for espresso enthusiasts!",
    rating: 4.8,
    coffee_id: 25,
    user_id: 2,
  },
  {
    first_name: "Jackson",
    last_name: "Anderson",
    text: "Oren's Special Blend is a well-crafted coffee. I give it a solid 4.0.",
    rating: 4.0,
    coffee_id: 26,
    user_id: 3,
  },
  {
    first_name: "Emma",
    last_name: "Jones",
    text: "East Coast is a well-balanced blend. Enjoyable for any coffee lover.",
    rating: 3.9,
    coffee_id: 26,
    user_id: 4,
  },
  {
    first_name: "Oliver",
    last_name: "Harrison",
    text: "Finca La Amistad has a unique and rich taste. Definitely worth trying!",
    rating: 4.2,
    coffee_id: 26,
    user_id: 5,
  },
  {
    first_name: "Sophia",
    last_name: "Martin",
    text: "Isreal Salazar is a smooth and flavorful coffee. Highly recommended!",
    rating: 4.7,
    coffee_id: 27,
    user_id: 1,
  },
  {
    first_name: "Liam",
    last_name: "Garcia",
    text: "Mejor is a top-notch coffee. Rich and satisfying!",
    rating: 4.5,
    coffee_id: 27,
    user_id: 2,
  },
  {
    first_name: "Ava",
    last_name: "Hernandez",
    text: "Dark Thunder is bold and intense. A perfect choice for espresso lovers!",
    rating: 4.6,
    coffee_id: 27,
    user_id: 3,
  },
  {
    first_name: "Jackson",
    last_name: "Anderson",
    text: "Yummy Decaf is surprisingly tasty! Perfect for late-night sipping.",
    rating: 4.3,
    coffee_id: 28,
    user_id: 4,
  },
  {
    first_name: "Emma",
    last_name: "Jones",
    text: "Beowulf Blend is bold and powerful. A great choice for espresso lovers.",
    rating: 4.5,
    coffee_id: 28,
    user_id: 5,
  },
  {
    first_name: "Oliver",
    last_name: "Harrison",
    text: "City Blend is a well-balanced coffee. Enjoying it every morning.",
    rating: 4.2,
    coffee_id: 28,
    user_id: 1,
  },
  {
    first_name: "Sophia",
    last_name: "Martin",
    text: "Colombian is a classic choice. Rich and flavorful!",
    rating: 4.0,
    coffee_id: 29,
    user_id: 2,
  },
  {
    first_name: "Liam",
    last_name: "Garcia",
    text: "Costa Rica La Minita is a smooth and bright coffee. Great for a morning pick-me-up.",
    rating: 4.3,
    coffee_id: 29,
    user_id: 3,
  },
  {
    first_name: "Ava",
    last_name: "Hernandez",
    text: "Italian Roast has a bold and intense flavor. Perfect for espresso enthusiasts!",
    rating: 4.8,
    coffee_id: 29,
    user_id: 4,
  },
  {
    first_name: "Jackson",
    last_name: "Anderson",
    text: "Oren's Special Blend is a well-crafted coffee. I give it a solid 4.0.",
    rating: 4.0,
    coffee_id: 30,
    user_id: 5,
  },
  {
    first_name: "Emma",
    last_name: "Jones",
    text: "East Coast is a well-balanced blend. Enjoyable for any coffee lover.",
    rating: 3.9,
    coffee_id: 30,
    user_id: 1,
  },
  {
    first_name: "Oliver",
    last_name: "Harrison",
    text: "Finca La Amistad has a unique and rich taste. Definitely worth trying!",
    rating: 4.2,
    coffee_id: 30,
    user_id: 2,
  },
];

module.exports = { reviews };
