import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import AuthContext from "./context/AuthContext";
import CartContextProvider from "./context/CartContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Coffee App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthContext>
					<CartContextProvider>
						<main>
							<NavBar />
							{children}
							<Footer />
						</main>
					</CartContextProvider>
				</AuthContext>
			</body>
		</html>
	);
}
